json.array! @motor_activities,
            :id,
            :date,
            :age,
            :smlresult,
            :blresult,
            :slresult,
            :mlresult,
            :hlresult,
            :created_at,
            :updated_at