json.extract! @motor_activity,
              :id,
              :date,
              :age,
              :smlresult,
              :blresult,
              :slresult,
              :mlresult,
              :hlresult,
              :created_at,
              :updated_at