json.array! @physical_preparedness_states,
            :id,
            :date,
            :age,
            :pushUps,
            :raising,
            :jumpLength,
            :jumpHeight,
            :estafeta,
            :cooperTest,
            :inclineBody,
            :flamingoTest,
            :inclines,
            :created_at,
            :updated_at