json.extract! @physical_preparedness_state,
              :id,
              :date,
              :age,
              :pushUps,
              :raising,
              :jumpLength,
              :jumpHeight,
              :estafeta,
              :cooperTest,
              :inclineBody,
              :flamingoTest,
              :inclines,
              :created_at,
              :updated_at