json.array! @definitions,
            :id,
            :age,
            :date,
            :calculatedProteins,
            :calculatedFats,
            :calculatedCarbohydrates,
            :calculatedCalories,
            :created_at,
            :updated_at