json.extract! @definition,
              :id,
              :age,
              :date,
              :proteins,
              :fats,
              :carbohydrates,
              :calories,
              :created_at,
              :updated_at