json.array! @physical_states,
            :id,
            :weight,
            :height,
            :volume,
            :circumference,
            :bodyindex,
            :lifeindex,
            :created_at,
            :updated_at