json.array! @physical_health_states,
            :id,
            :date,
            :age,
            :weight,
            :height,
            :volume,
            :pressure,
            :wrist,
            :pulse,
            :pulseRecovering,
            :result,
            :created_at,
            :updated_at