json.extract! @physical_health_state,
              :id,
              :date,
              :age,
              :weight,
              :height,
              :volume,
              :pressure,
              :wrist,
              :pulse,
              :pulseRecovering,
              :result,
              :created_at,
              :updated_at